export const themeNames = [
  'Agriculture, FoodTech & Rural Development',
  'Blockchain & Cybersecurity',
  'Clean & Green Technology',
  'Disaster Management',
  'Fitness & Sports',
  'Heritage & Culture',
  'MedTech / BioTech / HealthTech',
  'Miscellaneous',
  'Renewable / Sustainable Energy',
  'Robotics and Drones',
  'Smart Automation',
  'Smart Education',
  'Smart Vehicles',
  'Space Technology',
  'Toys & Games',
  'Transportation & Logistics',
  'Travel & Tourism',
];